<?php

if (!class_exists('Redux')) {
  return;
}

$opt_name = "medel_theme";
$opt_name = apply_filters('medel_theme/opt_name', $opt_name);

$theme = wp_get_theme();

$args = array(
  'opt_name' => $opt_name,
  'display_name' => $theme->get('Name'),
  'display_version' => $theme->get('Version'),
  'menu_type' => 'submenu',
  'allow_sub_menu' => true,
  'menu_title' => esc_html__('Theme Options', 'medel'),
  'page_title' => esc_html__('Theme Options', 'medel'),
  'google_api_key' => '',
  'google_update_weekly' => false,
  'async_typography' => true,
  'admin_bar' => false,
  'admin_bar_icon' => 'dashicons-portfolio',
  'admin_bar_priority' => 50,
  'global_variable' => '',
  'dev_mode' => false,
  'update_notice' => true,
  'customizer' => true,
  'page_priority' => null,
  'page_parent' => 'medel_dashboard',
  'page_permissions' => 'manage_options',
  'menu_icon' => '',
  'last_tab' => '',
  'page_icon' => 'icon-themes',
  'page_slug' => '',
  'save_defaults' => true,
  'default_show' => false,
  'default_mark' => '',
  'show_import_export' => true,
  'transient_time' => 60 * MINUTE_IN_SECONDS,
  'output' => true,
  'output_tag' => true,
  'database' => '',
  'use_cdn' => true,
  'show_options_object' => false,
);

Redux::setArgs($opt_name, $args);

function pt_social_icon() {
  return array(
    '' => esc_html__('---', 'medel'),
    'fa fa-500px,500px' => esc_html__('500px', 'medel'),
    'fa fa-adn,App.net' => esc_html__('App.net', 'medel'),
    'fa fa-bitbucket,Bitbucket' => esc_html__('Bitbucket', 'medel'),
    'fa fa-behance,Behance' => esc_html__('Behance', 'medel'),
    'fa fa-dribbble,Dribbble' => esc_html__('Dribbble', 'medel'),
    'fa fa-dropbox,Dropbox' => esc_html__('Dropbox', 'medel'),
    'fa fa-facebook,Facebook' => esc_html__('Facebook', 'medel'),
    'fa fa-flickr,Flickr' => esc_html__('Flickr', 'medel'),
    'fa fa-foursquare,Foursquare' => esc_html__('Foursquare', 'medel'),
    'fa fa-github,GitHub' => esc_html__('GitHub', 'medel'),
    'fa fa-google,Google' => esc_html__('Google', 'medel'),
    'fa fa-instagram,Instagram' => esc_html__('Instagram', 'medel'),
    'fa fa-linkedin,LinkedIn' => esc_html__('LinkedIn', 'medel'),
    'fa fa-windows,Windows' => esc_html__('Windows', 'medel'),
    'fa fa-odnoklassniki,Odnoklassniki' => esc_html__('Odnoklassniki', 'medel'),
    'fa fa-openid,OpenID' => esc_html__('OpenID', 'medel'),
    'fa fa-pinterest,Pinterest' => esc_html__('Pinterest', 'medel'),
    'fa fa-reddit,Reddit' => esc_html__('Reddit', 'medel'),
    'fa fa-soundcloud,SoundCloud' => esc_html__('SoundCloud', 'medel'),
    'fa fa-tumblr,Tumblr' => esc_html__('Tumblr', 'medel'),
    'fa fa-twitter,Twitter' => esc_html__('Twitter', 'medel'),
    'fa fa-vimeo,Vimeo' => esc_html__('Vimeo', 'medel'),
    'fa fa-vk,VK' => esc_html__('VK', 'medel'),
    'fa fa-yahoo,Yahoo' => esc_html__('Yahoo', 'medel'),
    'fa fa-youtube,Youtube' => esc_html__('Youtube', 'medel'),
  );
}

Redux::setSection($opt_name, array(
  'title' => esc_html__('General', 'medel'),
  'id' => 'general',
  'customizer_width' => '400px',
  'icon' => 'fa fa-home',
  'fields' => array(
    array(
      'id' => 'color_scheme',
      'type' => 'select',
      'title' => esc_html__('Color Scheme', 'medel'),
      'options' => array(
        'scheme1' => esc_html__('Scheme 1', 'medel'),
        'scheme2' => esc_html__('Scheme 2', 'medel'),
      ),
      'default' => 'scheme1',
    ),
    array(
      'id' => 'color_scheme1',
      'type' => 'color',
      'title' => esc_html__('Color Scheme 1', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array(
        'background-color' => '.site-header .header-top,.hm-cunt span,.minicart-wrap .buttons a.checkout, .widget_shopping_cart_content a.checkout,.button-style1,.button-style1:hover,.icon-box-item .top,.icon-box-item .wrap,.image-comparison-slider .line:after,.team-item .top,.site-footer.dark,.team-items .owl-prev, .team-items .owl-next, .testimonials .owl-prev, .testimonials .owl-next, .price-list.style2 .owl-prev, .price-list.style2 .owl-next, .price-list-type2 .owl-prev, .price-list-type2 .owl-next,.blog-item .wrap .date,.banner .owl-prev, .banner .owl-next,.woocommerce .products .product .add_to_cart_button,.category-item-style2 .h,.team-item-style2 .top,.price-list.style2 .top:after,.price-list-type2 .item .wrap:before,.button-style2,.woocommerce span.onsale,.woocommerce div.product form.cart .button,.woocommerce #payment #place_order, .woocommerce-page #payment #place_order,.site-content .date,.portfolio_hover_type_2 .portfolio-item .content h5:after,.portfolio_hover_type_4 .portfolio-item .content h5:after,.portfolio_hover_type_5 .portfolio-item .content h5:before,.portfolio_hover_type_6 .portfolio-item .content h5:after,.portfolio_hover_type_7 .portfolio-item .content h5:after, .portfolio_hover_type_7 .portfolio-item .content h5:before,.portfolio_hover_type_8 .portfolio-item .content h5:after, .portfolio_hover_type_8 .portfolio-item .content h5:before, .portfolio_hover_type_9 .portfolio-item .content h5:after, .portfolio_hover_type_9 .portfolio-item .content h5:before, .search-popup',
        'background' => '.skill-item .rating-line .line',
        'border-color' => '.header-minicart .minicart-wrap,.price-list .top:after,.woocommerce nav.woocommerce-pagination ul li a:focus, .woocommerce nav.woocommerce-pagination ul li a:hover, .woocommerce nav.woocommerce-pagination ul li span.current,.woocommerce div.product form.cart .variations select,.woocommerce table.shop_table.cart th,.woocommerce .shop_table div.quantity .input-text,.woocommerce-page .cart-collaterals .heading,.coupon-area .input-text,.woocommerce-billing-fields h4, .woocommerce-shipping-fields h4,.woocommerce form .form-row input.input-text, .woocommerce form .form-row textarea,.select2-container--default .select2-selection--single,.select2-dropdown,.comment-items .comment-item .image,.portfolio_hover_type_3 .portfolio-item .content, .portfolio_hover_type_6 .portfolio-item .content,.portfolio_hover_type_4 .portfolio-item .content,.portfolio_hover_type_4 .portfolio-item:hover .content, .woocommerce .cart-collaterals .heading-decor, .woocommerce-page .cart-collaterals .heading-decor, .woocommerce .cross-sells .products',
        'color' => '.navigation > ul > li.current-menu-item > a span, .navigation > ul > li.current-menu-ancestor > a span, .navigation > ul > li.current_page_item > a span, .navigation > ul > li.current-menu-ancestor > a span,.minicart-wrap .cart_list .mini_cart_item .quantity, .widget_shopping_cart_content .cart_list .mini_cart_item .quantity,.banner .h span,.scroll-next-screen,.heading-decor:after, .heading-decor-s .h:after,.wpb_text_column ul li:before, .site-content ul li:before,.minicart-wrap .total > span, .widget_shopping_cart_content .total > span,.navigation .sub-menu li.current-menu-item > a, .navigation .sub-menu li.current-menu-ancestor > a, .navigation .sub-menu li:hover > a, .navigation .sub-menu li.current-menu-item.menu-item-has-children:after, .navigation .sub-menu li:hover.menu-item-has-children:after, .navigation .children li.current_page_item > a, .navigation .children li.current-menu-ancestor > a, .navigation .children li:hover > a, .navigation .children li.current_page_item.page_item_has_children:after, .navigation .children li:hover.page_item_has_children:after,.testimonial-item,.blog-item .wrap,.banner-social-buttons a:hover,.woocommerce .products .product .price,.skill-item .rating-line > span,.icon-box-item-type2 .icon,.team-item-style2 .phone:before,.team-item-style2 .team-social-buttons,.testimonial-item-style2 .text:before, .testimonial-item-style2 .text:after,.navigation > ul > li:hover > a, .navigation > ul > li.current_page_item > a,.benefit-item .icon,.benefit-item .text .num,.woocommerce div.product .date,.woocommerce div.product .price-area,.woocommerce .cart .up, .woocommerce .cart .down,.woocommerce div.product .woocommerce-tabs .tabs li.active,.woocommerce .cart .up, .woocommerce .cart .down,.woocommerce-cart .cart-collaterals .cart_totals tr td .woocommerce-Price-amount,.woocommerce .cart-collaterals table.shop_table.woocommerce-checkout-review-order-table td .amount,.butter-button,.video-block a i:hover, .accordion-items .item .top .t:before, .accordion-items .item .top .t:after, .price-list .options .o-item:after, .woocommerce .products .product a.woocommerce-LoopProduct-link .name:hover',
        'stroke' => '.preloader-area .pulse svg polyline',
      ),
    ),
    array(
      'id' => 'color_scheme2',
      'type' => 'color',
      'title' => esc_html__('Color Scheme 2', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array(
        'background-color' => '.color-scheme2 .site-header .header-top,.color-scheme2 .hm-cunt span,.color-scheme2 .minicart-wrap .buttons a.checkout,.color-scheme2 .widget_shopping_cart_content a.checkout,.color-scheme2 .button-style1,.color-scheme2 .button-style1:hover,.color-scheme2 .icon-box-item .top,.color-scheme2 .icon-box-item .wrap,.color-scheme2 .image-comparison-slider .line:after,.color-scheme2 .team-item .top,.color-scheme2 .site-footer.dark,.color-scheme2 .team-items .owl-prev,.color-scheme2 .team-items .owl-next,.color-scheme2 .testimonials .owl-prev,.color-scheme2 .testimonials .owl-next,.color-scheme2 .price-list.style2 .owl-prev,.color-scheme2 .price-list.style2 .owl-next,.color-scheme2 .price-list-type2 .owl-prev,.color-scheme2 .price-list-type2 .owl-next,.color-scheme2 .blog-item .wrap .date,.color-scheme2 .banner .owl-prev,.color-scheme2 .banner .owl-next,.color-scheme2 .woocommerce .products .product .add_to_cart_button,.color-scheme2 .category-item-style2 .h,.color-scheme2 .team-item-style2 .top,.color-scheme2 .price-list.style2 .top:after,.color-scheme2 .price-list-type2 .item .wrap:before,.color-scheme2 .button-style2,.color-scheme2 .woocommerce span.onsale,.color-scheme2 .woocommerce div.product form.cart .button,.color-scheme2 .woocommerce #payment #place_order,.color-scheme2 .woocommerce-page #payment #place_order,.color-scheme2 .site-content .date,.color-scheme2 .portfolio_hover_type_2 .portfolio-item .content h5:after,.color-scheme2 .portfolio_hover_type_4 .portfolio-item .content h5:after,.color-scheme2 .portfolio_hover_type_5 .portfolio-item .content h5:before,.color-scheme2 .portfolio_hover_type_6 .portfolio-item .content h5:after,.color-scheme2 .portfolio_hover_type_7 .portfolio-item .content h5:after,.color-scheme2 .portfolio_hover_type_7 .portfolio-item .content h5:before,.color-scheme2 .portfolio_hover_type_8 .portfolio-item .content h5:after,.color-scheme2 .portfolio_hover_type_8 .portfolio-item .content h5:before,.color-scheme2 .portfolio_hover_type_9 .portfolio-item .content h5:after,.color-scheme2 .portfolio_hover_type_9 .portfolio-item .content h5:before,.color-scheme2 .search-popup',
        'background' => '.color-scheme2 .skill-item .rating-line .line',
        'border-color' => '.color-scheme2 .header-minicart .minicart-wrap,.color-scheme2 .price-list .top:after,.color-scheme2 .woocommerce nav.woocommerce-pagination ul li a:focus,.color-scheme2 .woocommerce nav.woocommerce-pagination ul li a:hover,.color-scheme2 .woocommerce nav.woocommerce-pagination ul li span.current,.color-scheme2 .woocommerce div.product form.cart .variations select,.color-scheme2 .woocommerce table.shop_table.cart th,.color-scheme2 .woocommerce .shop_table div.quantity .input-text,.color-scheme2 .woocommerce-page .cart-collaterals .heading,.color-scheme2 .coupon-area .input-text,.color-scheme2 .woocommerce-billing-fields h4,.color-scheme2 .woocommerce-shipping-fields h4,.color-scheme2 .woocommerce form .form-row input.input-text,.color-scheme2 .woocommerce form .form-row textarea,.color-scheme2 .select2-container--default .select2-selection--single,.color-scheme2 .select2-dropdown,.color-scheme2 .comment-items .comment-item .image,.color-scheme2 .portfolio_hover_type_3 .portfolio-item .content,.color-scheme2 .portfolio_hover_type_6 .portfolio-item .content,.color-scheme2 .portfolio_hover_type_4 .portfolio-item .content,.color-scheme2 .portfolio_hover_type_4 .portfolio-item:hover .content',
        'color' => '.color-scheme2 .navigation > ul > li.current-menu-item > a span,.color-scheme2 .navigation > ul > li.current-menu-ancestor > a span,.color-scheme2 .navigation > ul > li.current_page_item > a span,.color-scheme2 .navigation > ul > li.current-menu-ancestor > a span,.color-scheme2 .minicart-wrap .cart_list .mini_cart_item .quantity,.color-scheme2 .widget_shopping_cart_content .cart_list .mini_cart_item .quantity,.color-scheme2 .banner .h span,.color-scheme2 .scroll-next-screen,.color-scheme2 .heading-decor:after,.color-scheme2 .heading-decor-s .h:after,.color-scheme2 .wpb_text_column ul li:before,.color-scheme2 .site-content ul li:before,.color-scheme2 .minicart-wrap .total > span,.color-scheme2 .widget_shopping_cart_content .total > span,.color-scheme2 .navigation .sub-menu li.current-menu-item > a,.color-scheme2 .navigation .sub-menu li.current-menu-ancestor > a,.color-scheme2 .navigation .sub-menu li:hover > a,.color-scheme2 .navigation .sub-menu li.current-menu-item.menu-item-has-children:after,.color-scheme2 .navigation .sub-menu li:hover.menu-item-has-children:after,.color-scheme2 .navigation .children li.current_page_item > a,.color-scheme2 .navigation .children li.current-menu-ancestor > a,.color-scheme2 .navigation .children li:hover > a,.color-scheme2 .navigation .children li.current_page_item.page_item_has_children:after,.color-scheme2 .navigation .children li:hover.page_item_has_children:after,.color-scheme2 .testimonial-item,.color-scheme2 .blog-item .wrap,.color-scheme2 .banner-social-buttons a:hover,.color-scheme2 .woocommerce .products .product .price,.color-scheme2 .skill-item .rating-line > span,.color-scheme2 .icon-box-item-type2 .icon,.color-scheme2 .team-item-style2 .phone:before,.color-scheme2 .team-item-style2 .team-social-buttons,.color-scheme2 .testimonial-item-style2 .text:before,.color-scheme2 .testimonial-item-style2 .text:after,.color-scheme2 .navigation > ul > li:hover > a,.color-scheme2 .navigation > ul > li.current_page_item > a,.color-scheme2 .benefit-item .icon,.color-scheme2 .benefit-item .text .num,.color-scheme2 .woocommerce div.product .date,.color-scheme2 .woocommerce div.product .price-area,.color-scheme2 .woocommerce .cart .up,.color-scheme2 .woocommerce .cart .down,.color-scheme2 .woocommerce div.product .woocommerce-tabs .tabs li.active,.color-scheme2 .woocommerce .cart .up,.color-scheme2 .woocommerce .cart .down,.color-scheme2 .woocommerce-cart .cart-collaterals .cart_totals tr td .woocommerce-Price-amount,.color-scheme2 .woocommerce .cart-collaterals table.shop_table.woocommerce-checkout-review-order-table td .amount, .color-scheme2 .butter-button',
        'stroke' => '.color-scheme2 .preloader-area .pulse svg polyline,.color-scheme2 .video-block a i:hover, .color-scheme2 .woocommerce .products .product a.woocommerce-LoopProduct-link .name:hover, .color-scheme2 .accordion-items .item .top .t:before, .color-scheme2 .accordion-items .item .top .t:after',
      ),
    ),
  ),
));

Redux::setSection($opt_name, array(
  'title' => esc_html__('Preloader', 'medel'),
  'id' => 'general_preloader',
  'customizer_width' => '450px',
  'subsection' => true,
  'icon' => 'fa fa-spinner',
  'fields' => array(
    array(
      'id' => 'preloader_show',
      'type' => 'switch',
      'title' => esc_html__('Preloader', 'medel'),
      'default' => true,
    ),
    array(
      'id' => 'preloader_bg_color',
      'type' => 'color',
      'title' => esc_html__('Preloader background color', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('background' => '.preloader, .preloader-area'),
    ),
    array(
      'id' => 'preloader_img',
      'type' => 'background',
      'title' => esc_html__('Preloader image', 'medel'),
      'desc' => esc_html__('Choose a default logo image to display', 'medel'),
      'background-attachment' => false,
      'background-position' => false,
      'background-repeat' => false,
      'background-origin' => false,
      'background-color' => false,
      'background-size' => false,
      'background-clip' => false,
      'preview_media' => true,
      'preview' => false,
    ),
  ),
));

Redux::setSection($opt_name, array(
  'title' => esc_html__('Header', 'medel'),
  'id' => 'header',
  'customizer_width' => '400px',
  'icon' => 'fa fa-header',
  'fields' => array(
    array(
      'id' => 'working_time',
      'type' => 'text',
      'title' => esc_html__('Working time', 'medel'),
    ),
    array(
      'id' => 'phone_number',
      'type' => 'text',
      'title' => esc_html__('Phone number', 'medel'),
    ),
  ),
));

Redux::setSection($opt_name, array(
  'title' => esc_html__('Logo', 'medel'),
  'id' => 'header_logo',
  'customizer_width' => '450px',
  'subsection' => true,
  'icon' => 'fa fa-flag',
  'fields' => array(
    array(
      'id' => 'logo_text',
      'type' => 'text',
      'title' => esc_html__('Logo text', 'medel'),
    ),
    array(
      'id' => 'default_logo',
      'type' => 'background',
      'title' => esc_html__('Logo Image - normal', 'medel'),
      'desc' => esc_html__('Choose a default logo image to display', 'medel'),
      'background-attachment' => false,
      'background-position' => false,
      'background-repeat' => false,
      'background-origin' => false,
      'background-color' => false,
      'background-size' => false,
      'background-clip' => false,
      'preview_media' => true,
      'preview' => false,
    ),
    array(
      'id' => 'light_logo',
      'type' => 'background',
      'title' => esc_html__('Logo Image - light', 'medel'),
      'desc' => esc_html__('Choose a logo image to display for "Light" header skin', 'medel'),
      'background-attachment' => false,
      'background-position' => false,
      'background-repeat' => false,
      'background-origin' => false,
      'background-color' => false,
      'background-size' => false,
      'background-clip' => false,
      'preview_media' => true,
      'preview' => false,
    ),
    array(
      'id' => 'dark_logo',
      'type' => 'background',
      'title' => esc_html__('Logo Image - Dark', 'medel'),
      'desc' => esc_html__('Choose a logo image to display for "Dark" header skin', 'medel'),
      'background-attachment' => false,
      'background-position' => false,
      'background-repeat' => false,
      'background-origin' => false,
      'background-color' => false,
      'background-size' => false,
      'background-clip' => false,
      'preview_media' => true,
      'preview' => false,
    ),
    array(
      'id' => 'dark_logo_scheme2',
      'type' => 'background',
      'title' => esc_html__('Logo Image - Scheme 2', 'medel'),
      'desc' => esc_html__('Choose a logo image to display for "Dark" header skin', 'medel'),
      'background-attachment' => false,
      'background-position' => false,
      'background-repeat' => false,
      'background-origin' => false,
      'background-color' => false,
      'background-size' => false,
      'background-clip' => false,
      'preview_media' => true,
      'preview' => false,
    ),
    array(
      'id' => 'logo_size',
      'units' => 'px',
      'type' => 'dimensions',
      'units_extended' => 'false',
      'title' => esc_html__('Logo max width', 'medel'),
      'output' => array('.site-header .logo img, .side-header .logo img, .site-header .logo a, .side-header .logo a'),
      'height' => true,
      'default' => array(
        'Width' => '85',
      ),
    ),
  ),
));

Redux::setSection($opt_name, array(
  'title' => esc_html__('Header style', 'medel'),
  'id' => 'header_style',
  'customizer_width' => '450px',
  'subsection' => true,
  'icon' => 'fa fa-sliders',
  'fields' => array(
    array(
      'id' => 'header_container',
      'type' => 'select',
      'title' => esc_html__('Header container', 'medel'),
      'options' => array(
        'container' => esc_html__('Center container', 'medel'),
        'container-fluid' => esc_html__('Full witdh', 'medel'),
      ),
      'default' => 'container',
    ),
    array(
      'id' => 'header_color_mode',
      'type' => 'select',
      'title' => esc_html__('Header color mode', 'medel'),
      'options' => array(
        'dark' => esc_html__('Dark', 'medel'),
        'light' => esc_html__('Light', 'medel'),
      ),
      'default' => 'light',
    ),
    array(
      'id' => 'show_search',
      'type' => 'switch',
      'title' => esc_html__('Search', 'medel'),
      'default' => true,
    ),
    array(
      'id' => 'show_cart',
      'type' => 'switch',
      'title' => esc_html__('Cart', 'medel'),
      'default' => true,
    ),
    array(
      'id' => 'header_color_mode1',
      'type' => 'heading',
      'title' => esc_html__('Color Scheme 1', 'medel'),
    ),
    array(
      'id' => 'header_top_bg_color',
      'type' => 'color',
      'title' => esc_html__('Header Top Background Color', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('background-color' => '.site-header .header-top'),
    ),
    array(
      'id' => 'header_bg_color_light',
      'type' => 'color',
      'title' => esc_html__('Header Background Color for Light', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('background-color' => '.site-header.light'),
    ),
    array(
      'id' => 'header_bg_color_dark',
      'type' => 'color',
      'title' => esc_html__('Header Background Color for Dark', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('background-color' => '.site-header.dark'),
    ),
    array(
      'id' => 'header_text_light_color',
      'type' => 'color',
      'title' => esc_html__('Header Text Color for Light', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('color' => '.site-header.light'),
    ),
    array(
      'id' => 'header_text_dark_color',
      'type' => 'color',
      'title' => esc_html__('Header Text Color for Dark', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('color' => '.site-header.dark'),
    ),
    array(
      'id' => 'header_color_mode2',
      'type' => 'heading',
      'title' => esc_html__('Color Scheme 2', 'medel'),
    ),
    array(
      'id' => 'header_top_bg_color_scheme2',
      'type' => 'color',
      'title' => esc_html__('Header Top Background Color (Scheme 2)', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('background-color' => '.color-scheme2 .site-header .header-top'),
    ),
    array(
      'id' => 'header_bg_color_light_scheme2',
      'type' => 'color',
      'title' => esc_html__('Header Background Color for Light (Scheme 2)', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('background-color' => '.color-scheme2 .site-header.light'),
    ),
    array(
      'id' => 'header_bg_color_dark_scheme2',
      'type' => 'color',
      'title' => esc_html__('Header Background Color for Dark (Scheme 2)', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('background-color' => '.color-scheme2 .site-header.dark'),
    ),
    array(
      'id' => 'header_text_color_light_scheme2',
      'type' => 'color',
      'title' => esc_html__('Header Text Color for Light (Scheme 2)', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('color' => '.color-scheme2 .site-header.light'),
    ),
    array(
      'id' => 'header_text_color_dark_scheme2',
      'type' => 'color',
      'title' => esc_html__('Header Text Color for Dark (Scheme 2)', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('color' => '.color-scheme2 .site-header.dark'),
    ),
  ),
));

Redux::setSection($opt_name, array(
  'title' => esc_html__('Navigation', 'medel'),
  'id' => 'header_navigation',
  'customizer_width' => '450px',
  'subsection' => true,
  'icon' => 'fa fa-bars',
  'fields' => array(
    array(
      'id' => 'navigation_type',
      'type' => 'select',
      'title' => esc_html__('Navigation type', 'medel'),
      'options' => array(
        'disabled' => esc_html__('Disabled', 'medel'),
        'hidden_menu' => esc_html__('Hidden menu', 'medel'),
        'visible_menu' => esc_html__('Visible menu', 'medel'),
        'full_screen' => esc_html__('Full screen menu', 'medel'),
        'side' => esc_html__('Side', 'medel'),
      ),
      'default' => 'visible_menu',
    ),
  ),
));

Redux::setSection($opt_name, array(
  'title' => esc_html__('Typography', 'medel'),
  'id' => 'typography',
  'customizer_width' => '400px',
  'icon' => 'fa fa-font',
  'fields' => array(
    array(
      'id' => 'body-font-face',
      'type' => 'typography',
      'title' => esc_html__('Body', 'medel'),
      'google' => true,
      'font-backup' => true,
      'output' => array('body'),
      'units' => 'px',
      'text-align' => false,
      'line-height' => false,
      'subsets' => false,
      'all_styles' => true,
      'default' => array(
        'color' => '#222222',
        'font-style' => '300',
        'font-family' => 'Montserrat',
        'google' => true,
        'font-size' => '14px',
      ),
    ),
    array(
      'id' => 'h1-font-face',
      'type' => 'typography',
      'title' => esc_html__('H1', 'medel'),
      'google' => true,
      'font-backup' => true,
      'output' => array('h1, .h1'),
      'units' => 'px',
      'text-align' => false,
      'line-height' => false,
      'subsets' => false,
      'color' => false,
      'default' => array(
        'font-style' => '300',
        'font-family' => 'Montserrat',
        'google' => true,
        'font-size' => '48px',
      ),
    ),
    array(
      'id' => 'h2-font-face',
      'type' => 'typography',
      'title' => esc_html__('H2', 'medel'),
      'google' => true,
      'font-backup' => true,
      'output' => array('h2, .h2'),
      'units' => 'px',
      'text-align' => false,
      'line-height' => false,
      'subsets' => false,
      'color' => false,
      'default' => array(
        'font-style' => '300',
        'font-family' => 'Montserrat',
        'google' => true,
        'font-size' => '36px',
      ),
    ),
    array(
      'id' => 'h3-font-face',
      'type' => 'typography',
      'title' => esc_html__('H3', 'medel'),
      'google' => true,
      'font-backup' => true,
      'output' => array('h3, .h3'),
      'units' => 'px',
      'text-align' => false,
      'line-height' => false,
      'subsets' => false,
      'color' => false,
      'default' => array(
        'font-style' => '300',
        'font-family' => 'Montserrat',
        'google' => true,
        'font-size' => '30px',
      ),
    ),
    array(
      'id' => 'h4-font-face',
      'type' => 'typography',
      'title' => esc_html__('H4', 'medel'),
      'google' => true,
      'font-backup' => true,
      'output' => array('h4, .h4'),
      'units' => 'px',
      'text-align' => false,
      'line-height' => false,
      'subsets' => false,
      'color' => false,
      'default' => array(
        'font-style' => '300',
        'font-family' => 'Montserrat',
        'google' => true,
        'font-size' => '24px',
      ),
    ),
    array(
      'id' => 'h5-font-face',
      'type' => 'typography',
      'title' => esc_html__('H5', 'medel'),
      'google' => true,
      'font-backup' => true,
      'output' => array('h5, .h5'),
      'units' => 'px',
      'text-align' => false,
      'line-height' => false,
      'subsets' => false,
      'color' => false,
      'default' => array(
        'font-style' => '300',
        'font-family' => 'Montserrat',
        'google' => true,
        'font-size' => '18px',
      ),
    ),
    array(
      'id' => 'h6-font-face',
      'type' => 'typography',
      'title' => esc_html__('H6', 'medel'),
      'google' => true,
      'font-backup' => true,
      'output' => array('h6, .h6'),
      'units' => 'px',
      'text-align' => false,
      'line-height' => false,
      'subsets' => false,
      'color' => false,
      'default' => array(
        'font-style' => '300',
        'font-family' => 'Montserrat',
        'google' => true,
        'font-size' => '16px',
      ),
    ),
    array(
      'id' => 'additional-font-face',
      'type' => 'typography',
      'title' => esc_html__('Additional Font Face', 'medel'),
      'google' => true,
      'font-backup' => true,
      'units' => 'px',
      'text-align' => false,
      'line-height' => false,
      'subsets' => false,
      'font-weight' => false,
      'font-size' => false,
      'font-style' => false,
      'color' => false,
      'all_styles' => true,
    ),
    array(
      'id' => 'additional-font-face2',
      'type' => 'typography',
      'title' => esc_html__('Additional Font Face 2', 'medel'),
      'google' => true,
      'font-backup' => true,
      'units' => 'px',
      'text-align' => false,
      'line-height' => false,
      'subsets' => false,
      'font-weight' => false,
      'font-size' => false,
      'font-style' => false,
      'color' => false,
      'all_styles' => true,
    ),
    array(
      'id' => 'additional-font-face3',
      'type' => 'typography',
      'title' => esc_html__('Additional Font Face 3', 'medel'),
      'google' => true,
      'font-backup' => true,
      'units' => 'px',
      'text-align' => false,
      'line-height' => false,
      'subsets' => false,
      'font-weight' => false,
      'font-size' => false,
      'font-style' => false,
      'color' => false,
      'all_styles' => true,
    ),
    array(
      'id' => 'additional-font-face4',
      'type' => 'typography',
      'title' => esc_html__('Additional Font Face 4', 'medel'),
      'google' => true,
      'font-backup' => true,
      'units' => 'px',
      'text-align' => false,
      'line-height' => false,
      'subsets' => false,
      'font-weight' => false,
      'font-size' => false,
      'font-style' => false,
      'color' => false,
      'all_styles' => true,
    ),
  ),
));

Redux::setSection($opt_name, array(
  'title' => esc_html__('Social buttons', 'medel'),
  'id' => 'social_buttons',
  'customizer_width' => '400px',
  'icon' => 'fa fa-twitter',
  'fields' => array(
    array(
      'id' => 'social_target',
      'type' => 'select',
      'title' => esc_html__('Open link in', 'medel'),
      'options' => array(
        '_self' => esc_html__('Current Tab', 'medel'),
        '_blank' => esc_html__('New Tab', 'medel'),
      ),
    ),
    array(
      'id' => 'sl1',
      'type' => 'label',
      'title' => esc_html__('Social button 1', 'medel'),
    ),
    array(
      'id' => 'social_icon1',
      'type' => 'select',
      'title' => esc_html__('Social icon', 'medel'),
      'options' => pt_social_icon(),
      'default' => '',
    ),
    array(
      'id' => 'social_link1',
      'type' => 'text',
      'title' => esc_html__('Link', 'medel'),
    ),
    array(
      'id' => 'sb2',
      'type' => 'label',
      'title' => esc_html__('Social button 2', 'medel'),
    ),
    array(
      'id' => 'social_icon2',
      'type' => 'select',
      'title' => esc_html__('Social icon', 'medel'),
      'options' => pt_social_icon(),
      'default' => '',
    ),
    array(
      'id' => 'social_link2',
      'type' => 'text',
      'title' => esc_html__('Link', 'medel'),
    ),
    array(
      'id' => 'sb3',
      'type' => 'label',
      'title' => esc_html__('Social button 3', 'medel'),
    ),
    array(
      'id' => 'social_icon3',
      'type' => 'select',
      'title' => esc_html__('Social icon', 'medel'),
      'options' => pt_social_icon(),
      'default' => '',
    ),
    array(
      'id' => 'social_link3',
      'type' => 'text',
      'title' => esc_html__('Link', 'medel'),
    ),
    array(
      'id' => 'sb4',
      'type' => 'label',
      'title' => esc_html__('Social button 4', 'medel'),
    ),
    array(
      'id' => 'social_icon4',
      'type' => 'select',
      'title' => esc_html__('Social icon', 'medel'),
      'options' => pt_social_icon(),
      'default' => '',
    ),
    array(
      'id' => 'social_link4',
      'type' => 'text',
      'title' => esc_html__('Link', 'medel'),
    ),
    array(
      'id' => 'sb5',
      'type' => 'label',
      'title' => esc_html__('Social button 5', 'medel'),
    ),
    array(
      'id' => 'social_icon5',
      'type' => 'select',
      'title' => esc_html__('Social icon', 'medel'),
      'options' => pt_social_icon(),
      'default' => '',
    ),
    array(
      'id' => 'social_link5',
      'type' => 'text',
      'title' => esc_html__('Link', 'medel'),
    ),
    array(
      'id' => 'sb6',
      'type' => 'label',
      'title' => esc_html__('Social button 6', 'medel'),
    ),
    array(
      'id' => 'social_icon6',
      'type' => 'select',
      'title' => esc_html__('Social icon', 'medel'),
      'options' => pt_social_icon(),
      'default' => '',
    ),
    array(
      'id' => 'social_link6',
      'type' => 'text',
      'title' => esc_html__('Link', 'medel'),
    ),
    array(
      'id' => 'sb7',
      'type' => 'label',
      'title' => esc_html__('Social button 7', 'medel'),
    ),
    array(
      'id' => 'social_icon7',
      'type' => 'select',
      'title' => esc_html__('Social icon', 'medel'),
      'options' => pt_social_icon(),
      'default' => '',
    ),
    array(
      'id' => 'social_link7',
      'type' => 'text',
      'title' => esc_html__('Link', 'medel'),
    ),
  ),
));

Redux::setSection($opt_name, array(
  'title' => esc_html__('Footer', 'medel'),
  'id' => 'footer',
  'customizer_width' => '400px',
  'icon' => 'fa fa-th-list',
  'fields' => array(
    array(
      'id' => 'footer',
      'type' => 'select',
      'title' => esc_html__('Footer', 'medel'),
      'options' => array(
        'show' => esc_html__('Show', 'medel'),
        'hide' => esc_html__('Hide', 'medel'),
      ),
      'default' => 'show',
    ),
    array(
      'id' => 'footer_logo',
      'type' => 'select',
      'title' => esc_html__('Footer Logo', 'medel'),
      'options' => array(
        'show' => esc_html__('Show', 'medel'),
        'hide' => esc_html__('Hide', 'medel'),
      ),
      'default' => 'show',
    ),
    array(
      'id' => 'footer_social_buttons',
      'type' => 'select',
      'title' => esc_html__('Footer Social Buttons', 'medel'),
      'options' => array(
        'show' => esc_html__('Show', 'medel'),
        'hide' => esc_html__('Hide', 'medel'),
      ),
      'default' => 'show',
    ),
    array(
      'id' => 'footer_color_mode',
      'type' => 'select',
      'title' => esc_html__('Footer Color Mode', 'medel'),
      'options' => array(
        'dark' => esc_html__('Dark', 'medel'),
        'light' => esc_html__('Light', 'medel'),
      ),
      'default' => 'dark',
    ),
    array(
      'id' => 'footer_logo_size',
      'units' => 'px',
      'type' => 'dimensions',
      'units_extended' => 'false',
      'title' => esc_html__('Logo max width', 'medel'),
      'output' => array('.site-footer .logo img'),
      'height' => false,
      'default' => array(
        'Width' => '160',
      ),
    ),
    array(
      'id' => 'copyright_text',
      'type' => 'text',
      'title' => esc_html__('Copyright text', 'medel'),
    ),
    array(
      'id' => 'show_social_buttons',
      'type' => 'switch',
      'title' => esc_html__('Social buttons', 'medel'),
      'default' => true,
      'required' => array('show_footer_top', '=', 1),
    ),
    array(
      'id' => 'footer_col_1',
      'type' => 'select',
      'title' => esc_html__('Footer col 1', 'medel'),
      'options' => array(
        '1' => 'Col 1',
        '2' => 'Col 2',
        '3' => 'Col 3',
        '4' => 'Col 4',
        '5' => 'Col 5',
        '6' => 'Col 6',
        '7' => 'Col 7',
        '8' => 'Col 8',
        '9' => 'Col 9',
        '10' => 'Col 10',
        '11' => 'Col 11',
        '12' => 'Col 12',
      ),
      'default' => '3',
    ),
    array(
      'id' => 'footer_col_2',
      'type' => 'select',
      'title' => esc_html__('Footer col 2', 'medel'),
      'options' => array(
        '1' => 'Col 1',
        '2' => 'Col 2',
        '3' => 'Col 3',
        '4' => 'Col 4',
        '5' => 'Col 5',
        '6' => 'Col 6',
        '7' => 'Col 7',
        '8' => 'Col 8',
        '9' => 'Col 9',
        '10' => 'Col 10',
        '11' => 'Col 11',
        '12' => 'Col 12',
      ),
      'default' => '3',
    ),
    array(
      'id' => 'footer_col_3',
      'type' => 'select',
      'title' => esc_html__('Footer col 3', 'medel'),
      'options' => array(
        '1' => 'Col 1',
        '2' => 'Col 2',
        '3' => 'Col 3',
        '4' => 'Col 4',
        '5' => 'Col 5',
        '6' => 'Col 6',
        '7' => 'Col 7',
        '8' => 'Col 8',
        '9' => 'Col 9',
        '10' => 'Col 10',
        '11' => 'Col 11',
        '12' => 'Col 12',
      ),
      'default' => '3',
    ),
    array(
      'id' => 'footer_col_4',
      'type' => 'select',
      'title' => esc_html__('Footer col 4', 'medel'),
      'options' => array(
        '1' => 'Col 1',
        '2' => 'Col 2',
        '3' => 'Col 3',
        '4' => 'Col 4',
        '5' => 'Col 5',
        '6' => 'Col 6',
        '7' => 'Col 7',
        '8' => 'Col 8',
        '9' => 'Col 9',
        '10' => 'Col 10',
        '11' => 'Col 11',
        '12' => 'Col 12',
      ),
      'default' => '3',
    ),
    array(
      'id' => 'footer_color_mode1',
      'type' => 'heading',
      'title' => esc_html__('Color Scheme 1', 'medel'),
    ),
    array(
      'id' => 'footer_bg_color',
      'type' => 'color',
      'title' => esc_html__('Footer Background Color', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('background-color' => '.site-footer'),
    ),
    array(
      'id' => 'footer_text_color',
      'type' => 'color',
      'title' => esc_html__('Footer Text Color', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('color' => '.site-footer'),
    ),
    array(
      'id' => 'footer_color_mode2',
      'type' => 'heading',
      'title' => esc_html__('Color Scheme 2', 'medel'),
    ),
    array(
      'id' => 'footer_bg_color_scheme2',
      'type' => 'color',
      'title' => esc_html__('Footer Background Color (Scheme 2)', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('background-color' => '.color-scheme2 .site-footer'),
    ),
    array(
      'id' => 'footer_text_color_scheme2',
      'type' => 'color',
      'title' => esc_html__('Footer Text Color (Scheme 2)', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('color' => '.color-scheme2 .site-footer'),
    ),
  ),
));

Redux::setSection($opt_name, array(
  'title' => esc_html__('404 Page', 'medel'),
  'id' => '404_page',
  'customizer_width' => '400px',
  'icon' => 'fa fa-exclamation-circle',
  'fields' => array(
    array(
      'id' => 'header_color_mode_404',
      'type' => 'select',
      'title' => esc_html__('Header color mode', 'medel'),
      'options' => array(
        'dark' => esc_html__('Dark', 'medel'),
        'light' => esc_html__('Light', 'medel'),
      ),
      'default' => 'light',
    ),
    array(
      'id' => '404_bg',
      'type' => 'background',
      'title' => esc_html__('Background image', 'medel'),
      'background-attachment' => false,
      'background-position' => false,
      'background-repeat' => false,
      'background-origin' => false,
      'background-color' => false,
      'background-size' => false,
      'background-clip' => false,
      'preview_media' => true,
      'preview' => false,
    ),
    array(
      'id' => '404_page_color',
      'type' => 'color',
      'title' => esc_html__('Text color', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('color' => '.banner-404'),
    ),
    array(
      'id' => '404_page_heading_color',
      'type' => 'color',
      'title' => esc_html__('Heading color', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('color' => '.banner-404 .b-404-heading'),
    ),
    array(
      'id' => '404_page_heading',
      'type' => 'textarea',
      'title' => esc_html__('Heading', 'medel'),
      'default' => __('<span>404 error</span>', 'medel'),
    ),
    array(
      'id' => '404_page_desc',
      'type' => 'textarea',
      'title' => esc_html__('Desc', 'medel'),
      'default' => esc_html__('You are on a non existings page', 'medel'),
    ),
  ),
));

Redux::setSection($opt_name, array(
  'title' => esc_html__('Coming soon page', 'medel'),
  'id' => 'coming_soon',
  'customizer_width' => '400px',
  'icon' => 'fa fa-clock-o',
  'fields' => array(
    array(
      'id' => 'header_color_mode_coming_soon',
      'type' => 'select',
      'title' => esc_html__('Header color mode', 'medel'),
      'options' => array(
        'dark' => esc_html__('Dark', 'medel'),
        'light' => esc_html__('Light', 'medel'),
      ),
      'default' => 'light',
    ),
    array(
      'id' => 'coming_soon_bg',
      'type' => 'background',
      'title' => esc_html__('Background image', 'medel'),
      'background-attachment' => false,
      'background-position' => false,
      'background-repeat' => false,
      'background-origin' => false,
      'background-color' => false,
      'background-size' => false,
      'background-clip' => false,
      'preview_media' => true,
      'preview' => false,
    ),
    array(
      'id' => 'coming_soon_color',
      'type' => 'color',
      'title' => esc_html__('Text color', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('color' => '.banner-coming-soon'),
    ),
    array(
      'id' => 'coming_soon_heading_color',
      'type' => 'color',
      'title' => esc_html__('Heading color', 'medel'),
      'validate' => 'color',
      'transparent' => false,
      'output' => array('color' => '.banner-coming-soon .b-coming-heading'),
    ),
    array(
      'id' => 'coming_soon_heading',
      'type' => 'textarea',
      'title' => esc_html__('Heading', 'medel'),
      'default' => esc_html__('Coming soon', 'medel'),
    ),
    array(
      'id' => 'coming_soon_subscribe_desc',
      'type' => 'textarea',
      'title' => esc_html__('Subscribe form desc', 'medel'),
      'default' => esc_html__('Subscribe and get the latest information about us.', 'medel'),
    ),
    array(
      'id' => 'coming_soon_subscribe_code',
      'type' => 'text',
      'title' => esc_html__('Subscribe form code', 'medel'),
    ),
  ),
));

Redux::setSection($opt_name, array(
  'title' => esc_html__('Project page', 'medel'),
  'id' => 'project_page',
  'customizer_width' => '400px',
  'icon' => 'fa fa-file-text',
  'fields' => array(
    array(
      'id' => 'project_style',
      'type' => 'select',
      'title' => esc_html__('Style project page', 'medel'),
      'options' => array(
        'slider' => esc_html__('Slider', 'medel'),
        'masonry' => esc_html__('Masonry', 'medel'),
      ),
      'default' => 'slider',
    ),
    array(
      'id' => 'project_image',
      'type' => 'select',
      'title' => esc_html__('Project image', 'medel'),
      'options' => array(
        'full' => esc_html__('Full', 'medel'),
        'adaptive' => esc_html__('Adaptive', 'medel'),
      ),
      'default' => 'full',
    ),
  ),
));

Redux::setSection($opt_name, array(
  'title' => esc_html__('Blog post', 'medel'),
  'id' => 'blog_post',
  'customizer_width' => '400px',
  'icon' => 'fa fa-wordpress',
  'fields' => array(
    array(
      'id' => 'blog_feature_image',
      'type' => 'select',
      'title' => esc_html__('Blog feature image', 'medel'),
      'options' => array(
        'hide' => esc_html__('Hide', 'medel'),
        'show' => esc_html__('Show', 'medel'),
      ),
      'default' => 'show',
    ),
    array(
      'id' => 'blog_date',
      'type' => 'select',
      'title' => esc_html__('Show date', 'medel'),
      'options' => array(
        'show' => esc_html__('Show', 'medel'),
        'hide' => esc_html__('Hide', 'medel'),
      ),
      'default' => 'show',
    ),
  ),
));

Redux::setSection($opt_name, array(
  'title' => esc_html__('Google Maps API', 'medel'),
  'id' => 'google_maps_api',
  'customizer_width' => '400px',
  'icon' => 'fa fa-map-pin',
  'fields' => array(
    array(
      'id' => 'google_maps_api_key',
      'type' => 'text',
      'title' => esc_html__('Google Map API Key', 'medel'),
      'description' => __('Create an application in <a href="https://console.developers.google.com/flows/enableapi?apiid=places_backend,maps_backend,geocoding_backend,directions_backend,distance_matrix_backend,elevation_backend&keyType=CLIENT_SIDE&reusekey=true" target="_blank">Google Console</a> and add the Key here.', 'medel'),
    ),
  ),
));